# filename: config.toml
[database]
server = "127.0.0.1"
port = "3306"
database = "test"
user = "root"
password1 = "12345678"

addr = "localhost:6379"
password = ""

[output]
directory = "./output"
format = "toml"


